/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#dee8ff",
        "primary": "#6b38d4",
        "error": "#ba1a1a",
        "surface-variant": "#d8e3fb",
        "on-tertiary-container": "#fbfdff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#23005c",
        "inverse-surface": "#263143",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-tertiary-fixed-variant": "#444749",
        "error-container": "#ffdad6",
        "on-surface": "#111c2d",
        "surface-container-low": "#f0f3ff",
        "primary-fixed-dim": "#d0bcff",
        "on-secondary-fixed": "#001e2f",
        "inverse-on-surface": "#ecf1ff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#89ceff",
        "on-surface-variant": "#494454",
        "on-secondary-container": "#004666",
        "secondary-fixed": "#c9e6ff",
        "tertiary-fixed": "#e0e3e5",
        "surface-tint": "#6d3bd7",
        "secondary-container": "#39b8fd",
        "on-tertiary-fixed": "#191c1e",
        "surface-container-highest": "#d8e3fb",
        "primary-container": "#8455ef",
        "surface": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#727577",
        "background": "#f9f9ff",
        "on-error-container": "#93000a",
        "inverse-primary": "#d0bcff",
        "surface-container": "#e7eeff",
        "surface-dim": "#cfdaf2",
        "primary-fixed": "#e9ddff",
        "on-secondary-fixed-variant": "#004c6e",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#5516be",
        "tertiary": "#595c5e",
        "outline-variant": "#cbc3d7",
        "on-error": "#ffffff",
        "secondary": "#006591",
        "outline": "#7b7486",
        "surface-bright": "#f9f9ff",
        "on-primary-container": "#fffbff",
        "on-background": "#111c2d"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "unit": "8px",
        "stack-sm": "8px",
        "gutter": "24px",
        "stack-md": "16px",
        "section-gap": "80px",
        "container-max-width": "1200px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
